name = "Project Crowbar"
author = "Nikk"
version = "260907"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cdae1e09196f690f1dbcb4b5da0d5ec781349124c528770203cf9fa1240fbdd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
