name = "Project Crowbar"
author = "Nikk"
version = "260907"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "060faf6a302916d332e2578233b6ef886fd8b2a5763bdcebd001c1db895904a0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
